## Simple SDL mini code
 
CC= gcc
 
CPPFLAGS=
CFLAGS= -Wall -Wextra -Werror -std=c99 -O3
LDFLAGS=
LDLIBS= 
 
SRC= list.c
OBJ= ${SRC:.c=.o}
 
all: list
 
main: ${OBJ}
 
clean:
	rm -f *~ *.o
	rm -f list
 
# END
